# Generated by Django 4.1.7 on 2023-05-10 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('acute bed', 'Acute bed'), ('swing bed', 'Swing bed')], default='swing bed', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_Id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalId', models.CharField(max_length=6, null=True, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mortality_rate', models.FloatField(null=True)),
                ('covid_vaccination', models.CharField(max_length=255, null=True)),
                ('pressure_ulcers', models.CharField(max_length=255, null=True)),
                ('complaints', models.CharField(max_length=255, null=True)),
                ('hires', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient')], default='doctor', max_length=255)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=255, null=True)),
                ('emergency_room', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True)),
                ('medical_advice', models.CharField(choices=[('against medical advice', 'Against medical advice'), ('with medical advice', 'With medical advice')], max_length=255, null=True)),
                ('patient_id', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('admission_date', models.DateTimeField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(null=True)),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpatient', models.IntegerField()),
                ('swing_bed', models.IntegerField()),
                ('observation', models.IntegerField()),
                ('emergency_room', models.IntegerField(null=True)),
                ('outpatient', models.IntegerField()),
                ('rural_health_clinic', models.IntegerField()),
                ('date_entered', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
            options={
                'verbose_name_plural': 'Census',
            },
        ),
    ]
