# Generated by Django 4.1.7 on 2023-04-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('acute bed', 'Acute bed'), ('swing bed', 'Swing bed')], default='swing bed', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_room', models.IntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('patient', 'Patient')], default='doctor', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('status', models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], default='Inpatient', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.user')),
                ('hospital', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark', models.DateTimeField()),
                ('bed_transfers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.bed')),
                ('emergency_room_transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EmergencyRoomTransfer', to='dashboard.hospital')),
                ('medication_errors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.user')),
                ('mortality_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.hospital')),
                ('pressure_ulcer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PressurEulcer', to='dashboard.hospital')),
                ('readmissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient')),
            ],
            options={
                'verbose_name_plural': 'Measures',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('complainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpatient', models.IntegerField(null=True)),
                ('benchmark', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.bed')),
                ('census', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient')),
            ],
            options={
                'verbose_name_plural': 'Census',
            },
        ),
    ]
