# Generated by Django 4.1.7 on 2023-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='turnover',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
