# Generated by Django 4.1.7 on 2023-05-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('voluntary', models.IntegerField()),
                ('date_entered', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality_rate', models.CharField(max_length=255, null=True)),
                ('readmissions', models.IntegerField()),
                ('pressure_ulcer', models.IntegerField()),
                ('discharges_home', models.IntegerField()),
                ('emergency_room_transfers', models.IntegerField()),
                ('acute_swing_bed_transfers', models.IntegerField()),
                ('medication_errors', models.IntegerField()),
                ('falls', models.IntegerField()),
                ('against_medical_advice', models.IntegerField()),
                ('left_without_being_seen', models.IntegerField()),
                ('hospital_acquired_infection', models.IntegerField()),
                ('covid_vaccination_total_percentage_of_compliance', models.IntegerField()),
                ('complaint', models.IntegerField()),
                ('grievances', models.IntegerField()),
                ('date_entered', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
            options={
                'verbose_name_plural': 'Measures',
            },
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_hires', models.IntegerField()),
                ('date_entered', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
        ),
    ]
