# Generated by Django 4.1.7 on 2023-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_hospital_turnover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalId',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
