# Generated by Django 4.1.7 on 2023-05-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_turnover_measures_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measures',
            name='mortality_rate',
            field=models.IntegerField(null=True),
        ),
    ]
