# Generated by Django 4.1.7 on 2023-05-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230510_1332'),
        ('dashboard', '0003_alter_measures_mortality_rate'),
    ]

    operations = [
    ]
