# Generated by Django 4.1.7 on 2023-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_hospital_hospitalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='turnover_date',
            field=models.DateField(null=True),
        ),
    ]
