# Generated by Django 4.1.7 on 2023-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20230511_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnover',
            name='total',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
