# Generated by Django 4.1.7 on 2023-05-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_hospital_turnover_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='turnover',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='turnover_date',
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover_date', models.DateField(null=True)),
                ('turnover', models.IntegerField(max_length=255, null=True)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
        ),
    ]
