# Generated by Django 4.1.7 on 2023-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_turnover_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_installable', models.BooleanField(default=False)),
                ('installable_description', models.TextField()),
                ('is_UI_intuitive', models.BooleanField(default=False)),
                ('intuitive_description', models.TextField()),
                ('are_features_clear', models.BooleanField(default=False)),
                ('features_description', models.TextField()),
                ('are_expectations_met', models.BooleanField(default=False)),
                ('expectations_descriptions', models.TextField()),
                ('is_bug_free', models.BooleanField(default=False)),
                ('bug_description', models.TextField()),
                ('is_quick', models.BooleanField(default=False)),
                ('quick_description', models.TextField()),
                ('satification_rate', models.CharField(choices=[('strongly_dissatisfied', '0-10'), ('quite_dissatisfied', '11-30'), ('dissatisfied', '31-50'), ('satisfied', '51-60'), ('quite_satisfied', '61-80'), ('strongly_satisfied', '81-100')], max_length=21)),
            ],
        ),
        migrations.AlterField(
            model_name='measures',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
