# Generated by Django 4.1.7 on 2023-05-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_hospital_turnover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnover',
            old_name='Hospital',
            new_name='hospital',
        ),
    ]
