# Generated by Django 4.1.7 on 2023-06-07 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_feedback_alter_measures_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='additional_feature',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='are_expectations_met',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='are_features_clear',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_UI_intuitive',
            field=models.BooleanField(default=True, verbose_name=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_bug_free',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_installable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_quick',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
