# Generated by Django 4.1.7 on 2023-06-07 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_feedback_additional_feature_feedback_feedback_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='satification_rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
