# Generated by Django 4.1.7 on 2023-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_customuser_email_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
