# Generated by Django 4.1.7 on 2023-06-07 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_feedback_satification_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='satification_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
