# Generated by Django 4.1.7 on 2023-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_phone_hospital_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospitalId',
            field=models.IntegerField(null=True),
        ),
    ]
