# Generated by Django 4.1.7 on 2023-06-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_feedback_satification_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='satification_description',
            new_name='satisfaction_description',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='satification_rate',
            new_name='satisfaction_rate',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_UI_intuitive',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
