# Generated by Django 4.1.7 on 2023-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_hospital_mortality_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='covid_vaccination',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
