# Generated by Django 4.1.7 on 2023-06-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_satification_description_feedback_satisfaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='satisfaction_rate',
            field=models.CharField(choices=[('strongly_dissatisfied', '0-10'), ('quite_dissatisfied', '11-30'), ('dissatisfied', '31-50'), ('satisfied', '51-60'), ('quite_satisfied', '61-80'), ('strongly_satisfied', '81-100')], max_length=21),
        ),
    ]
