# Generated by Django 4.1.7 on 2023-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_hospital_pressure_ulcers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='complaints',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
