# Generated by Django 4.1.7 on 2023-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_feedback_satisfaction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='hospital',
            field=models.CharField(max_length=144, null=True),
        ),
    ]
