# Generated by Django 4.1.7 on 2023-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_hospital_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hires',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
