# Generated by Django 4.1.7 on 2023-04-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_hospital_hires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='emergency_rooms',
        ),
    ]
