# Generated by Django 4.1.7 on 2023-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_hospital_emergency_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_Id',
            field=models.IntegerField(null=True),
        ),
    ]
