# Generated by Django 4.1.7 on 2023-04-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_department_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
