# Generated by Django 4.1.7 on 2023-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_customuser_is_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientId',
            field=models.IntegerField(null=True),
        ),
    ]
