# Generated by Django 4.1.7 on 2023-04-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_patient_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_number',
            field=models.IntegerField(default=0),
        ),
    ]
