# Generated by Django 4.1.7 on 2023-04-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_bed_bed_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_number',
        ),
    ]
