# Generated by Django 4.1.7 on 2023-04-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_rename_customuser_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patientId',
            new_name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_room',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_advice',
            field=models.CharField(choices=[('against medical advice', 'Against medical advice'), ('with medical advice', 'With medical advice')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.profile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient')], max_length=255, null=True),
        ),
    ]
