# Generated by Django 4.1.7 on 2023-04-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_rename_second_name_patient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
