# Generated by Django 4.1.7 on 2023-05-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_patient_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='mortality_rate',
            field=models.IntegerField(null=True),
        ),
    ]
