# Generated by Django 4.1.7 on 2023-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_hospital_mortality_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='mortality_rate',
            field=models.FloatField(null=True),
        ),
    ]
