# Generated by Django 4.1.7 on 2023-05-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_patient_admission_date'),
        ('dashboard', '0030_patient_admission_date'),
    ]

    operations = [
    ]
